user: deploy
group: deploy
timeout: 30
wait: 30
log: /var/www/broadcast-web/logs/thin.log
max_conns: 1024
environment: production
max_persistent_conns: 100
port: 3000
threaded: true
no-epoll: true
daemonize: true
pid: /var/www/broadcast-web/tmp/pids/thin.pid
chdir: /var/www/broadcast-web/current
tag: broadcast-web
